# Starter pipeline 

# Start with a minimal pipeline that you can customize to build and deploy your code. 

# Add steps that build, run tests, deploy, and more: 

# https://aka.ms/yaml 

  

trigger: 

- main 

  

pool: 

  vmImage: 'ubuntu-latest' 

  

steps: 
- script: docker pull katalonstudio/katalon
  displayName: 'Pull katalon studio images'
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
  displayName: 'Runnning Katalon TS_RegressionTest'
- task: PowerShell@2 

  inputs: 

    targetType: 'inline' 

    script: | 

       Copy-Item -Path * -Destination $(Build.ArtifactStagingDirectory) -Recurse 

- task: CmdLine@2 

  inputs: 

    script: | 

      echo locnt 

       

      echo $(Build.ArtifactStagingDirectory) 

- task: PublishBuildArtifacts@1 

  inputs: 

    PathtoPublish: '$(Build.ArtifactStagingDirectory)' 

    ArtifactName: 'source' 

    publishLocation: 'Container' 